services:
    tleroch_admin.security:
        class: Tleroch\AdminBundle\Services\Security
        arguments: ["@request_stack", "@service_container"]

    tleroch_admin.file_uploader:
        class: Tleroch\AdminBundle\Services\FileUploader
        arguments: ['@service_container']